// 簡中
// const sortedObjectByKey = require('./../utils/sortObjectByKey');

const zh_CN = {
  phrases: {
    'assembly language': '彙編語言',
    'cloud computing': '雲計算',
    'connection-oriented': '面向連接',
    'constructor function': '構造函數',
    'domain name': '域名',
    'flash memory': '閃存',
    'high level language': '高級語言',
    'indent-based': '縮進',
    'lazy loading': '懶加載',
    'low level language': '低級語言',
    'object-oriented': '面向對象',
    'plan text': '純文本',
    'production mode': '生成模式',
    'source code': '源代碼',
  },
  words: {
    activated: '激活的',
    animation: '動效',
    array: '數組',
    asynchronous: '異步',
    attribute: '特性',
    bandwidth: '帶寬',
    base: '進制',
    block: '塊',
    blog: '博客',
    byte: '字節',
    cache: '緩存',
    call: '調用',
    callback: '回調',
    character: '字符',
    client: '客戶端',
    cluster: '集群',
    code: '代碼',
    command: '命令',
    community: '社區',
    compatible: '兼容',
    create: '創建',
    data: '數據',
    deactivated: '失活的',
    debug: '調試',
    default: '默認',
    document: '文檔',
    example: '示例',
    export: '導出',
    extension: '擴展名',
    fallback: '後備',
    file: '文件',
    folder: '文件夾',
    gateway: '網關',
    homepage: '主頁',
    import: '導入',
    inline: '內聯',
    interface: '界面',
    internet: '互聯網',
    iterator: '遍歷器',
    lan: '局域網',
    link: '鏈接',
    list: '列表',
    load: '加載',
    login: '登陸',
    loop: '循環',
    match: '匹配',
    memory: '內存',
    message: '信息',
    module: '模塊',
    motherboard: '母板',
    mouse: '鼠標',
    navigation: '導航',
    nested: '嵌套',
    network: '網絡',
    object: '對象',
    online: '在線',
    packet: '報文',
    port: '端口',
    post: '帖子',
    printer: '打印機',
    process: '進程',
    program: '程序',
    programmer: '程序員',
    programming: '編程',
    protocol: '協議',
    recursion: '遞歸',
    redirect: '重定向',
    refresh: '刷新',
    register: '寄存器',
    response: '響應',
    return: '返回',
    reuse: '復用',
    runtime: '運行',
    scheduling: '調度',
    screen: '屏幕',
    scroll: '滾動',
    scrollbar: '滾動條',
    server: '服務器',
    setting: '設置',
    setting_2: '配置',
    stack: '堆棧',
    submit: '提交',
    template: '模板',
    text: '文本',
    thread: '線程',
    transition: '過渡',
    uninstall: '卸載',
    user: '用戶',
    variable: '變量',
    window: '窗口',
  },
};

// console.log(sortedObjectByKey(zh_CN));

export default zh_CN;
