// 簡中
const sortedObjectByKey = require('./../utilities/sortObjectByKey');

const zh_CN = {
  phrases: {
    'assembly language': '彙編語言',
    'connection-oriented': '面向連接',
    'cloud computing': '雲計算',
    'domain name': '域名',
    'high level language': '高級語言',
    'low level language': '低級語言',
    'object-oriented': '面向對象',
    'plan text': '純文本',
    'production mode': '生成模式',
    'source code': '源代碼'
  },
  words: {
    array: '數組',
    asynchronous: '異步',
    attribute: '特性',
    bandwidth: '帶寬',
    blog: '博客',
    byte: '字節',
    cache: '緩存',
    call: '調用',
    character: '字符',
    client: '客戶端',
    cluster: '集群',
    code: '代碼',
    command: '命令',
    community: '社區',
    compatile: '兼容',
    data: '數據',
    default: '默認值',
    document: '文檔',
    extension: '擴展名',
    export: '導出',
    file: '文件',
    folder: '文件夾',
    import: '導入',
    inline: '內聯',
    internet: '互聯網',
    lan: '局域網',
    list: '列表',
    load: '加載',
    login: '登陸',
    homepage: '主頁',
    memory: '內存',
    module: '模塊',
    motherboard: '母板',
    mouse: '鼠標',
    network: '網絡',
    object: '對象',
    online: '在線',
    packet: '報文',
    port: '端口',
    post: '帖子',
    process: '進程',
    program: '程序'
    programmer: '程序員',
    programming: '編程',
    protocol: '協議',
    refresh: '刷新',
    register: '寄存器',
    return: '返回',
    scheduling: '調度',
    screen: '屏幕',
    server: '服務器',
    settting: '設置',
    stack: '堆棧',
    submit: '提交',
    uninstall: '卸載',
    variable: '變量',
    window: '窗口'
  }
};

// console.log(sortedObjectByKey(zh_CN));

export default zh_CN;
