// 繁中
// const sortedObjectByKey = require('./../utilities/sortObjectByKey');

const zh_TW = {
  phrases: {
    "assembly language": "組合語言",
    "cloud computing": "雲端運算",
    "connection-oriented": "連結導向",
    "constructor function": "建構式函式",
    "domain name": "網域名稱",
    "flash memory": "快閃記憶體",
    "high level language": "高階語言",
    "low level language": "低階語言",
    "object-oriented": "物件導向",
    "plan text": "純文字",
    "production mode": "正式模式",
    "source code": "原始碼"
  },
  words: {
    array: "陣列",
    asynchronous: "非同步",
    attribute: "屬性",
    bandwidth: "頻寬",
    base: "進位",
    block: "區塊",
    blog: "部落格",
    byte: "位元組",
    cache: "快取",
    call: "呼叫",
    character: "字元",
    client: "用戶端",
    cluster: "叢集",
    code: "程式碼",
    command: "指令",
    community: "社群",
    compatible: "相容",
    component: "元件",
    computer: "電腦",
    create: "建立",
    data: "資料",
    debug: "偵錯",
    default: "預設值",
    default_2: "預設值",
    document: "文件",
    example: "範例",
    export: "匯出",
    extension: "副檔名",
    file: "檔案",
    folder: "資料夾",
    gateway: "閘道器",
    homepage: "首頁",
    import: "匯入",
    indent_based: "縮排",
    inline: "行內",
    internet: "網際網路",
    iterator: "疊代器",
    lan: "區域網路",
    list: "清單",
    load: "載入",
    login: "登入",
    loop: "迴圈",
    match: "對應",
    memory: "記憶體",
    message: "訊息",
    module: "模組",
    motherboard: "主機板",
    mouse: "滑鼠",
    network: "網路",
    object: "物件",
    online: "線上",
    packet: "封包",
    port: "連接埠",
    post: "文章",
    printer: "印表機",
    process: "程序",
    program: "程式",
    programmer: "工程師",
    programming: "程式設計",
    protocol: "協定",
    runtime: "執行",
    recursion: "遞迴",
    refresh: "重新整理",
    register: "暫存器",
    response: "回應",
    return: "回傳",
    scheduling: "排程",
    screen: "螢幕",
    server: "伺服器",
    setting: "設定",
    setting_2: "設定",
    stack: "堆疊",
    submit: "送出",
    template: "樣板",
    template_2: "樣板",
    text: "文字",
    thread: "執行緒",
    transition: "轉場",
    uninstall: "解除安裝",
    user: "使用者",
    variable: "變數",
    window: "視窗"
  }
};

// console.log(sortedObjectByKey(zh_TW));

export default zh_TW;
